# Generated by Django 2.2.5 on 2019-09-16 13:56

import annoying.fields
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailUser',
            fields=[
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detailuser', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('userinfo', models.CharField(blank=True, max_length=1000, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255, verbose_name='房间名字')),
                ('room_introduction', models.CharField(max_length=255, verbose_name='房间介绍（粗略）')),
                ('room_count', models.CharField(max_length=255, verbose_name='房间可容纳人数')),
                ('room_use', models.CharField(max_length=255, verbose_name='房间用途')),
                ('room_image', models.URLField(max_length=255, verbose_name='房间图片')),
            ],
            options={
                'verbose_name': '房间',
                'verbose_name_plural': '房间',
            },
        ),
        migrations.CreateModel(
            name='SettingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=255, verbose_name='书院名字')),
                ('content', ckeditor.fields.RichTextField(verbose_name='书院介绍')),
            ],
            options={
                'verbose_name': '书院',
                'verbose_name_plural': '书院',
            },
        ),
        migrations.CreateModel(
            name='Reserver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='预约的开始时间')),
                ('end_time', models.TimeField(verbose_name='预约的结束时间')),
                ('date', models.DateField(verbose_name='预约日期')),
                ('name', models.CharField(max_length=255, verbose_name='活动名称')),
                ('belong', models.CharField(blank=True, max_length=255, null=True, verbose_name='活动所属组织或个人')),
                ('event_intro', models.CharField(blank=True, max_length=500, null=True, verbose_name='活动描述')),
                ('contact_method', models.CharField(choices=[('phone', '手机'), ('wx', '微信'), ('qq', 'QQ')], max_length=255, verbose_name='用什么联系')),
                ('contact_info', models.CharField(max_length=255, verbose_name='联系方式')),
                ('datecreat', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomDetail', to='wxdaka.Room', verbose_name='预约的房间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='预约的用户')),
            ],
            options={
                'verbose_name': '预约',
                'verbose_name_plural': '预约',
                'ordering': ['-datecreat'],
            },
        ),
    ]
