# Generated by Django 2.2.5 on 2019-09-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxdaka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WxInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesstoken', models.CharField(max_length=255, verbose_name='企业微信私匙')),
            ],
        ),
    ]
