# Generated by Django 2.2.5 on 2019-09-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxdaka', '0002_wxinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxinfo',
            name='accesstoken',
            field=models.CharField(max_length=500, verbose_name='企业微信私匙'),
        ),
    ]
