# Generated by Django 2.2.5 on 2019-09-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxdaka', '0003_auto_20190917_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserver',
            name='is_activate',
            field=models.BooleanField(default=False, verbose_name='预约是否有效'),
        ),
    ]
