# Generated by Django 2.2.5 on 2019-09-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxdaka', '0004_reserver_is_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserver',
            name='formid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='表单ID'),
        ),
    ]
