# Generated by Django 2.2.5 on 2019-09-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxdaka', '0005_reserver_formid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserver',
            name='is_activate',
            field=models.BooleanField(default=True, verbose_name='预约是否有效'),
        ),
    ]
