# Generated by Django 2.2.5 on 2019-10-07 08:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxdaka', '0006_auto_20190917_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserver',
            name='is_activate',
            field=models.BooleanField(default=False, verbose_name='预约是否有效'),
        ),
        migrations.AlterField(
            model_name='settingmodel',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='书院介绍'),
        ),
    ]
