# Generated by Django 2.2.5 on 2019-10-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxdaka', '0007_auto_20191007_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingmodel',
            name='college_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='书院名字'),
        ),
    ]
